### ISSUE TITLE
it seems not compatible with redmine_pivot_table

### ISSUE THREAD

**Issue by archonwang** [charleneChen/issues_tree_table#1]
it seems not compatible with redmine_pivot_table（https://github.com/deecay/redmine_pivot_table）,  please help me to check it. Thanks.

the error log is 

> Started GET "/projects/zmss/pivottables" for 192.168.60.238 at 2016-11-07 19:10:33 +0800
> Processing by PivottablesController#index as HTML
>   Parameters: {"project_id"=>"zmss"}
>   Current user: hui.wang (id=8)
> Completed 500 Internal Server Error in 140ms (ActiveRecord: 70.8ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_request.text.erb (0.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_session.text.erb (1.2ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_environment.text.erb (2.3ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/_title.text.erb (0.1ms)
>   Rendered /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/exception_notification-4.2.1/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb (13.4ms)
> 
> NoMethodError (undefined method `count' for nil:NilClass):
>   plugins/redmine_issues_tree_view/lib/issue_query_patch.rb:18:in `issues_with_tree_view'
>   plugins/redmine_pivot_table/app/controllers/pivottables_controller.rb:62:in `index'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
>

**Comment by charleneChen** [comment]
Oops! I will check it later...

**Comment by charleneChen** [comment]
@archonwang I just updated and it should work now.

**Comment by archonwang** [comment]
@charlenechen
thanks， it works!!
